version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - aws --version

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t ebpr-auth-server-image ./

  post_build:
    commands:
      - echo Build completed on `date`
      - docker save -o ebpr-auth-server-image.tar ebpr-auth-server-image:latest

artifacts:
  files:
    - '**/*'


