version: 0.2

runtime-versions:
  ruby: 3.1

env:
  variables:
    DEPLOY_APPNAME: "mhclg-epb-auth-server-production"
    EPB_API_DOCS_URL: "https://api-docs.epcregisters.net/"

  parameter-store:
    PAAS_LOGIN: "epbr-govpaas-production-login"
    PAAS_PW: "epbr-govpaas-production-pw"
    PAAS_SPACE: "epbr-govpaas-production-space"
    PAAS_API: "epbr-govpaas-api"
    PAAS_ORG: "epbr-govpaas-orgname"
    JWT_ISSUER: "epbr-jwt-issuer-production"
    JWT_SECRET: "epbr-jwt-secret-production"
    EPB_UNLEASH_URI: "epbr-unleash-production-uri"
    EPB_UNLEASH_AUTH_TOKEN: "epbr-unleash-production-auth-token"
    PERMANENTLY_BANNED_IP_ADDRESSES: "epbr-permanently-banned-ip-addresses"
    SENTRY_DSN: "epbr-sentry-dsn-auth-server"

phases:
  install:
    runtime-versions:
      ruby: 3.1
  pre_build:
    commands:
      - cf login -a $PAAS_API -u $PAAS_LOGIN -p "$PAAS_PW" -o $PAAS_ORG -s $PAAS_SPACE
      - cf cancel-deployment ${DEPLOY_APPNAME} || true
  build:
    commands:
      - make deploy-app
      - make migrate-db-and-wait-for-success
  post_build:
    commands:
      - cf logout
