version: 0.2

runtime-versions:
  ruby: 2.7.2

env:
  variables:
    DEPLOY_APPNAME: "mhclg-epb-auth-server-production"

  parameter-store:
    PAAS_LOGIN: "epbr-govpaas-production-login"
    PAAS_PW: "epbr-govpaas-production-pw"
    PAAS_SPACE: "epbr-govpaas-production-space"
    PAAS_API: "epbr-govpaas-api"
    PAAS_ORG: "epbr-govpaas-orgname"
    EPB_UNLEASH_URI: "epbr-unleash-production-uri"
    JWT_ISSUER: "epbr-jwt-issuer-production"
    JWT_SECRET: "epbr-jwt-secret-production"

phases:
  install:
    runtime-versions:
      ruby: 2.7.2
  pre_build:
    commands:
      - cf login -a $PAAS_API -u $PAAS_LOGIN -p "$PAAS_PW" -o $PAAS_ORG -s $PAAS_SPACE
      - cf cancel-deployment ${DEPLOY_APPNAME} || true
  build:
    commands:
      - make deploy-app
      - make migrate-db-and-wait-for-success
  post_build:
    commands:
      - cf logout
