default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: localhost
  port: 5432
  database: auth_development

test:
  <<: *default
  host: localhost
  port: 5432
  database: auth_test
